global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "dynamodb-local"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "self"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "fastapi-app"
    static_configs:
      - targets: ["host.docker.internal:8080"]